services:
  - type: web
    name: face-recognition-attendance
    runtime: docker
    plan: free
    branch: main
    rootDir: FaceRecognitionAttendance
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: face_attendance
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false